on:
  pull_request:
  push:
    branches: [main, master]

name: pre-commit

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        with:
          limit-access-to-actor: true

      - name: Run pre-commit checks
        uses: ccao-data/actions/pre-commit@main
