on:
  pull_request:
  push:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run R test coverage
        uses: ccao-data/actions/test-coverage-r@jeancochrane/28-refactor-test-coverage-action-for-r-packages
